# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/protocol_1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import protocol_0_pb2 as bnet_dot_protocol__0__pb2
from .protocol import attribute_pb2 as bnet_dot_protocol_dot_attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/protocol_1.proto',
  package='bnet.protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x62net/protocol_1.proto\x12\rbnet.protocol\x1a\x15\x62net/protocol_0.proto\x1a\x1d\x62net/protocol/attribute.proto\"J\n\rObjectAddress\x12&\n\x04host\x18\x01 \x01(\x0b\x32\x18.bnet.protocol.ProcessId\x12\x11\n\tobject_id\x18\x02 \x01(\x04\"z\n\tErrorInfo\x12\x34\n\x0eobject_address\x18\x01 \x01(\x0b\x32\x1c.bnet.protocol.ObjectAddress\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x14\n\x0cservice_hash\x18\x03 \x01(\r\x12\x11\n\tmethod_id\x18\x04 \x01(\r\"\xa9\x01\n\x06Header\x12\x12\n\nservice_id\x18\x01 \x01(\r\x12\x11\n\tmethod_id\x18\x02 \x01(\r\x12\r\n\x05token\x18\x03 \x01(\r\x12\x11\n\tobject_id\x18\x04 \x01(\x04\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x0e\n\x06status\x18\x06 \x01(\r\x12\'\n\x05\x65rror\x18\x07 \x03(\x0b\x32\x18.bnet.protocol.ErrorInfo\x12\x0f\n\x07timeout\x18\x08 \x01(\x04\"\xbe\x01\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tprivilege\x18\x03 \x03(\t\x12\x17\n\x0f\x61ssignable_role\x18\x04 \x03(\r\x12\x10\n\x08required\x18\x05 \x01(\x08\x12\x0e\n\x06unique\x18\x06 \x01(\x08\x12\x17\n\x0frelegation_role\x18\x07 \x01(\r\x12\x35\n\tattribute\x18\x08 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"\xca\x01\n\x07RoleSet\x12\x0f\n\x07program\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x18\n\x07subtype\x18\x03 \x01(\t:\x07\x64\x65\x66\x61ult\x12!\n\x04role\x18\x04 \x03(\x0b\x32\x13.bnet.protocol.Role\x12\x14\n\x0c\x64\x65\x66\x61ult_role\x18\x05 \x03(\r\x12\x13\n\x0bmax_members\x18\x06 \x01(\x05\x12\x35\n\tattribute\x18\x07 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"f\n\rRoleSetConfig\x12+\n\tprivilege\x18\x01 \x03(\x0b\x32\x18.bnet.protocol.Privilege\x12(\n\x08role_set\x18\x02 \x01(\x0b\x32\x16.bnet.protocol.RoleSet')
  ,
  dependencies=[bnet_dot_protocol__0__pb2.DESCRIPTOR,bnet_dot_protocol_dot_attribute__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OBJECTADDRESS = _descriptor.Descriptor(
  name='ObjectAddress',
  full_name='bnet.protocol.ObjectAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='bnet.protocol.ObjectAddress.host', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='bnet.protocol.ObjectAddress.object_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=168,
)


_ERRORINFO = _descriptor.Descriptor(
  name='ErrorInfo',
  full_name='bnet.protocol.ErrorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_address', full_name='bnet.protocol.ErrorInfo.object_address', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='bnet.protocol.ErrorInfo.status', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_hash', full_name='bnet.protocol.ErrorInfo.service_hash', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_id', full_name='bnet.protocol.ErrorInfo.method_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=292,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='bnet.protocol.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_id', full_name='bnet.protocol.Header.service_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_id', full_name='bnet.protocol.Header.method_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='bnet.protocol.Header.token', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='bnet.protocol.Header.object_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='bnet.protocol.Header.size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='bnet.protocol.Header.status', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='bnet.protocol.Header.error', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='bnet.protocol.Header.timeout', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=464,
)


_ROLE = _descriptor.Descriptor(
  name='Role',
  full_name='bnet.protocol.Role',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.Role.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.Role.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='privilege', full_name='bnet.protocol.Role.privilege', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assignable_role', full_name='bnet.protocol.Role.assignable_role', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required', full_name='bnet.protocol.Role.required', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unique', full_name='bnet.protocol.Role.unique', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relegation_role', full_name='bnet.protocol.Role.relegation_role', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.Role.attribute', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=657,
)


_ROLESET = _descriptor.Descriptor(
  name='RoleSet',
  full_name='bnet.protocol.RoleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.RoleSet.program', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service', full_name='bnet.protocol.RoleSet.service', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtype', full_name='bnet.protocol.RoleSet.subtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("default").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='bnet.protocol.RoleSet.role', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_role', full_name='bnet.protocol.RoleSet.default_role', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_members', full_name='bnet.protocol.RoleSet.max_members', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.RoleSet.attribute', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=862,
)


_ROLESETCONFIG = _descriptor.Descriptor(
  name='RoleSetConfig',
  full_name='bnet.protocol.RoleSetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='privilege', full_name='bnet.protocol.RoleSetConfig.privilege', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role_set', full_name='bnet.protocol.RoleSetConfig.role_set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=864,
  serialized_end=966,
)

_OBJECTADDRESS.fields_by_name['host'].message_type = bnet_dot_protocol__0__pb2._PROCESSID
_ERRORINFO.fields_by_name['object_address'].message_type = _OBJECTADDRESS
_HEADER.fields_by_name['error'].message_type = _ERRORINFO
_ROLE.fields_by_name['attribute'].message_type = bnet_dot_protocol_dot_attribute__pb2._ATTRIBUTE
_ROLESET.fields_by_name['role'].message_type = _ROLE
_ROLESET.fields_by_name['attribute'].message_type = bnet_dot_protocol_dot_attribute__pb2._ATTRIBUTE
_ROLESETCONFIG.fields_by_name['privilege'].message_type = bnet_dot_protocol__0__pb2._PRIVILEGE
_ROLESETCONFIG.fields_by_name['role_set'].message_type = _ROLESET
DESCRIPTOR.message_types_by_name['ObjectAddress'] = _OBJECTADDRESS
DESCRIPTOR.message_types_by_name['ErrorInfo'] = _ERRORINFO
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Role'] = _ROLE
DESCRIPTOR.message_types_by_name['RoleSet'] = _ROLESET
DESCRIPTOR.message_types_by_name['RoleSetConfig'] = _ROLESETCONFIG

ObjectAddress = _reflection.GeneratedProtocolMessageType('ObjectAddress', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTADDRESS,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.ObjectAddress)
  ))
_sym_db.RegisterMessage(ObjectAddress)

ErrorInfo = _reflection.GeneratedProtocolMessageType('ErrorInfo', (_message.Message,), dict(
  DESCRIPTOR = _ERRORINFO,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.ErrorInfo)
  ))
_sym_db.RegisterMessage(ErrorInfo)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Header)
  ))
_sym_db.RegisterMessage(Header)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), dict(
  DESCRIPTOR = _ROLE,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.Role)
  ))
_sym_db.RegisterMessage(Role)

RoleSet = _reflection.GeneratedProtocolMessageType('RoleSet', (_message.Message,), dict(
  DESCRIPTOR = _ROLESET,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.RoleSet)
  ))
_sym_db.RegisterMessage(RoleSet)

RoleSetConfig = _reflection.GeneratedProtocolMessageType('RoleSetConfig', (_message.Message,), dict(
  DESCRIPTOR = _ROLESETCONFIG,
  __module__ = 'bnet.protocol_1_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.RoleSetConfig)
  ))
_sym_db.RegisterMessage(RoleSetConfig)


# @@protoc_insertion_point(module_scope)
