# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleJSON.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimpleJSON.proto',
  package='SimpleJSON',
  syntax='proto2',
  serialized_pb=_b('\n\x10SimpleJSON.proto\x12\nSimpleJSON*n\n\rJSONBinaryTag\x12\t\n\x05\x41rray\x10\x01\x12\t\n\x05\x43lass\x10\x02\x12\t\n\x05Value\x10\x03\x12\x0c\n\x08IntValue\x10\x04\x12\x0f\n\x0b\x44oubleValue\x10\x05\x12\r\n\tBoolValue\x10\x06\x12\x0e\n\nFloatValue\x10\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_JSONBINARYTAG = _descriptor.EnumDescriptor(
  name='JSONBinaryTag',
  full_name='SimpleJSON.JSONBinaryTag',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Array', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Class', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Value', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntValue', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoubleValue', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BoolValue', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FloatValue', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=32,
  serialized_end=142,
)
_sym_db.RegisterEnumDescriptor(_JSONBINARYTAG)

JSONBinaryTag = enum_type_wrapper.EnumTypeWrapper(_JSONBINARYTAG)
Array = 1
Class = 2
Value = 3
IntValue = 4
DoubleValue = 5
BoolValue = 6
FloatValue = 7


DESCRIPTOR.enum_types_by_name['JSONBinaryTag'] = _JSONBINARYTAG


# @@protoc_insertion_point(module_scope)
