// Code generated by protoc-gen-go.
// source: bnet/protocol/friends.proto
// DO NOT EDIT!

/*
Package bnet_protocol_friends is a generated protocol buffer package.

It is generated from these files:
	bnet/protocol/friends.proto

It has these top-level messages:
	AssignRoleRequest
	Friend
	FriendNotification
	GenericFriendRequest
	GenericFriendResponse
	SubscribeToFriendsRequest
	UnsubscribeToFriendsRequest
	UpdateFriendStateNotification
	UpdateFriendStateRequest
	ViewFriendsRequest
	ViewFriendsResponse
	FriendInvitation
	InvitationNotification
	FriendInvitationParams
	SubscribeToFriendsResponse
*/
package bnet_protocol_friends

import proto "github.com/golang/protobuf/proto"
import math "math"
import bnet_protocol "bnet"
import bnet_protocol_attribute "bnet/protocol"
import bnet_protocol_invitation "bnet/protocol"
import bnet_protocol1 "bnet"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type AssignRoleRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	TargetId         *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=target_id" json:"target_id,omitempty"`
	Role             []int32                 `protobuf:"varint,3,rep,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *AssignRoleRequest) Reset()         { *m = AssignRoleRequest{} }
func (m *AssignRoleRequest) String() string { return proto.CompactTextString(m) }
func (*AssignRoleRequest) ProtoMessage()    {}

func (m *AssignRoleRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *AssignRoleRequest) GetTargetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *AssignRoleRequest) GetRole() []int32 {
	if m != nil {
		return m.Role
	}
	return nil
}

type Friend struct {
	Id               *bnet_protocol.EntityId              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Attribute        []*bnet_protocol_attribute.Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	Role             []uint32                             `protobuf:"varint,3,rep,name=role" json:"role,omitempty"`
	Privileges       *uint64                              `protobuf:"varint,4,opt,name=privileges" json:"privileges,omitempty"`
	AttributesEpoch  *uint64                              `protobuf:"varint,5,opt,name=attributes_epoch" json:"attributes_epoch,omitempty"`
	FullName         *string                              `protobuf:"bytes,6,opt,name=full_name" json:"full_name,omitempty"`
	BattleTag        *string                              `protobuf:"bytes,7,opt,name=battle_tag" json:"battle_tag,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}

func (m *Friend) GetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Friend) GetAttribute() []*bnet_protocol_attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Friend) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Friend) GetPrivileges() uint64 {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return 0
}

func (m *Friend) GetAttributesEpoch() uint64 {
	if m != nil && m.AttributesEpoch != nil {
		return *m.AttributesEpoch
	}
	return 0
}

func (m *Friend) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

func (m *Friend) GetBattleTag() string {
	if m != nil && m.BattleTag != nil {
		return *m.BattleTag
	}
	return ""
}

type FriendNotification struct {
	Target           *Friend                 `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	GameAccountId    *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=game_account_id" json:"game_account_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *FriendNotification) Reset()         { *m = FriendNotification{} }
func (m *FriendNotification) String() string { return proto.CompactTextString(m) }
func (*FriendNotification) ProtoMessage()    {}

func (m *FriendNotification) GetTarget() *Friend {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *FriendNotification) GetGameAccountId() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

type GenericFriendRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	TargetId         *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GenericFriendRequest) Reset()         { *m = GenericFriendRequest{} }
func (m *GenericFriendRequest) String() string { return proto.CompactTextString(m) }
func (*GenericFriendRequest) ProtoMessage()    {}

func (m *GenericFriendRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *GenericFriendRequest) GetTargetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

type GenericFriendResponse struct {
	TargetFriend     *Friend `protobuf:"bytes,1,opt,name=target_friend" json:"target_friend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenericFriendResponse) Reset()         { *m = GenericFriendResponse{} }
func (m *GenericFriendResponse) String() string { return proto.CompactTextString(m) }
func (*GenericFriendResponse) ProtoMessage()    {}

func (m *GenericFriendResponse) GetTargetFriend() *Friend {
	if m != nil {
		return m.TargetFriend
	}
	return nil
}

type SubscribeToFriendsRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	ObjectId         *uint64                 `protobuf:"varint,2,opt,name=object_id" json:"object_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SubscribeToFriendsRequest) Reset()         { *m = SubscribeToFriendsRequest{} }
func (m *SubscribeToFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToFriendsRequest) ProtoMessage()    {}

func (m *SubscribeToFriendsRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeToFriendsRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type UnsubscribeToFriendsRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	ObjectId         *uint64                 `protobuf:"varint,2,opt,name=object_id" json:"object_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UnsubscribeToFriendsRequest) Reset()         { *m = UnsubscribeToFriendsRequest{} }
func (m *UnsubscribeToFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeToFriendsRequest) ProtoMessage()    {}

func (m *UnsubscribeToFriendsRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeToFriendsRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type UpdateFriendStateNotification struct {
	ChangedFriend    *Friend                 `protobuf:"bytes,1,opt,name=changed_friend" json:"changed_friend,omitempty"`
	GameAccountId    *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=game_account_id" json:"game_account_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateFriendStateNotification) Reset()         { *m = UpdateFriendStateNotification{} }
func (m *UpdateFriendStateNotification) String() string { return proto.CompactTextString(m) }
func (*UpdateFriendStateNotification) ProtoMessage()    {}

func (m *UpdateFriendStateNotification) GetChangedFriend() *Friend {
	if m != nil {
		return m.ChangedFriend
	}
	return nil
}

func (m *UpdateFriendStateNotification) GetGameAccountId() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

type UpdateFriendStateRequest struct {
	AgentId          *bnet_protocol.EntityId              `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	TargetId         *bnet_protocol.EntityId              `protobuf:"bytes,2,opt,name=target_id" json:"target_id,omitempty"`
	Attribute        []*bnet_protocol_attribute.Attribute `protobuf:"bytes,3,rep,name=attribute" json:"attribute,omitempty"`
	AttributesEpoch  *uint64                              `protobuf:"varint,4,opt,name=attributes_epoch" json:"attributes_epoch,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *UpdateFriendStateRequest) Reset()         { *m = UpdateFriendStateRequest{} }
func (m *UpdateFriendStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFriendStateRequest) ProtoMessage()    {}

func (m *UpdateFriendStateRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UpdateFriendStateRequest) GetTargetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *UpdateFriendStateRequest) GetAttribute() []*bnet_protocol_attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *UpdateFriendStateRequest) GetAttributesEpoch() uint64 {
	if m != nil && m.AttributesEpoch != nil {
		return *m.AttributesEpoch
	}
	return 0
}

type ViewFriendsRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	TargetId         *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=target_id" json:"target_id,omitempty"`
	Role             []uint32                `protobuf:"varint,3,rep,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ViewFriendsRequest) Reset()         { *m = ViewFriendsRequest{} }
func (m *ViewFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*ViewFriendsRequest) ProtoMessage()    {}

func (m *ViewFriendsRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *ViewFriendsRequest) GetTargetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *ViewFriendsRequest) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

type ViewFriendsResponse struct {
	Friends          []*Friend `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ViewFriendsResponse) Reset()         { *m = ViewFriendsResponse{} }
func (m *ViewFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*ViewFriendsResponse) ProtoMessage()    {}

func (m *ViewFriendsResponse) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type FriendInvitation struct {
	FirstReceived    *bool    `protobuf:"varint,1,opt,name=first_received" json:"first_received,omitempty"`
	Role             []uint32 `protobuf:"varint,2,rep,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FriendInvitation) Reset()         { *m = FriendInvitation{} }
func (m *FriendInvitation) String() string { return proto.CompactTextString(m) }
func (*FriendInvitation) ProtoMessage()    {}

func (m *FriendInvitation) GetFirstReceived() bool {
	if m != nil && m.FirstReceived != nil {
		return *m.FirstReceived
	}
	return false
}

func (m *FriendInvitation) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

var E_FriendInvitation_FriendInvite = &proto.ExtensionDesc{
	ExtendedType:  (*bnet_protocol_invitation.Invitation)(nil),
	ExtensionType: (*FriendInvitation)(nil),
	Field:         103,
	Name:          "bnet.protocol.friends.FriendInvitation.friend_invite",
	Tag:           "bytes,103,opt,name=friend_invite",
}

type InvitationNotification struct {
	Invitation       *bnet_protocol_invitation.Invitation `protobuf:"bytes,1,opt,name=invitation" json:"invitation,omitempty"`
	GameAccountId    *bnet_protocol.EntityId              `protobuf:"bytes,2,opt,name=game_account_id" json:"game_account_id,omitempty"`
	Reason           *uint32                              `protobuf:"varint,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *InvitationNotification) Reset()         { *m = InvitationNotification{} }
func (m *InvitationNotification) String() string { return proto.CompactTextString(m) }
func (*InvitationNotification) ProtoMessage()    {}

func (m *InvitationNotification) GetInvitation() *bnet_protocol_invitation.Invitation {
	if m != nil {
		return m.Invitation
	}
	return nil
}

func (m *InvitationNotification) GetGameAccountId() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

func (m *InvitationNotification) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type FriendInvitationParams struct {
	TargetEmail        *string  `protobuf:"bytes,1,opt,name=target_email" json:"target_email,omitempty"`
	TargetBattleTag    *string  `protobuf:"bytes,2,opt,name=target_battle_tag" json:"target_battle_tag,omitempty"`
	InviterBattleTag   *string  `protobuf:"bytes,3,opt,name=inviter_battle_tag" json:"inviter_battle_tag,omitempty"`
	InviterFullName    *string  `protobuf:"bytes,4,opt,name=inviter_full_name" json:"inviter_full_name,omitempty"`
	InviteeDisplayName *string  `protobuf:"bytes,5,opt,name=invitee_display_name" json:"invitee_display_name,omitempty"`
	Role               []uint32 `protobuf:"varint,6,rep,name=role" json:"role,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *FriendInvitationParams) Reset()         { *m = FriendInvitationParams{} }
func (m *FriendInvitationParams) String() string { return proto.CompactTextString(m) }
func (*FriendInvitationParams) ProtoMessage()    {}

func (m *FriendInvitationParams) GetTargetEmail() string {
	if m != nil && m.TargetEmail != nil {
		return *m.TargetEmail
	}
	return ""
}

func (m *FriendInvitationParams) GetTargetBattleTag() string {
	if m != nil && m.TargetBattleTag != nil {
		return *m.TargetBattleTag
	}
	return ""
}

func (m *FriendInvitationParams) GetInviterBattleTag() string {
	if m != nil && m.InviterBattleTag != nil {
		return *m.InviterBattleTag
	}
	return ""
}

func (m *FriendInvitationParams) GetInviterFullName() string {
	if m != nil && m.InviterFullName != nil {
		return *m.InviterFullName
	}
	return ""
}

func (m *FriendInvitationParams) GetInviteeDisplayName() string {
	if m != nil && m.InviteeDisplayName != nil {
		return *m.InviteeDisplayName
	}
	return ""
}

func (m *FriendInvitationParams) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

var E_FriendInvitationParams_FriendParams = &proto.ExtensionDesc{
	ExtendedType:  (*bnet_protocol_invitation.InvitationParams)(nil),
	ExtensionType: (*FriendInvitationParams)(nil),
	Field:         103,
	Name:          "bnet.protocol.friends.FriendInvitationParams.friend_params",
	Tag:           "bytes,103,opt,name=friend_params",
}

type SubscribeToFriendsResponse struct {
	MaxFriends             *uint32                                `protobuf:"varint,1,opt,name=max_friends" json:"max_friends,omitempty"`
	MaxReceivedInvitations *uint32                                `protobuf:"varint,2,opt,name=max_received_invitations" json:"max_received_invitations,omitempty"`
	MaxSentInvitations     *uint32                                `protobuf:"varint,3,opt,name=max_sent_invitations" json:"max_sent_invitations,omitempty"`
	Role                   []*bnet_protocol1.Role                 `protobuf:"bytes,4,rep,name=role" json:"role,omitempty"`
	Friends                []*Friend                              `protobuf:"bytes,5,rep,name=friends" json:"friends,omitempty"`
	SentInvitations        []*bnet_protocol_invitation.Invitation `protobuf:"bytes,6,rep,name=sent_invitations" json:"sent_invitations,omitempty"`
	ReceivedInvitations    []*bnet_protocol_invitation.Invitation `protobuf:"bytes,7,rep,name=received_invitations" json:"received_invitations,omitempty"`
	XXX_unrecognized       []byte                                 `json:"-"`
}

func (m *SubscribeToFriendsResponse) Reset()         { *m = SubscribeToFriendsResponse{} }
func (m *SubscribeToFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeToFriendsResponse) ProtoMessage()    {}

func (m *SubscribeToFriendsResponse) GetMaxFriends() uint32 {
	if m != nil && m.MaxFriends != nil {
		return *m.MaxFriends
	}
	return 0
}

func (m *SubscribeToFriendsResponse) GetMaxReceivedInvitations() uint32 {
	if m != nil && m.MaxReceivedInvitations != nil {
		return *m.MaxReceivedInvitations
	}
	return 0
}

func (m *SubscribeToFriendsResponse) GetMaxSentInvitations() uint32 {
	if m != nil && m.MaxSentInvitations != nil {
		return *m.MaxSentInvitations
	}
	return 0
}

func (m *SubscribeToFriendsResponse) GetRole() []*bnet_protocol1.Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *SubscribeToFriendsResponse) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *SubscribeToFriendsResponse) GetSentInvitations() []*bnet_protocol_invitation.Invitation {
	if m != nil {
		return m.SentInvitations
	}
	return nil
}

func (m *SubscribeToFriendsResponse) GetReceivedInvitations() []*bnet_protocol_invitation.Invitation {
	if m != nil {
		return m.ReceivedInvitations
	}
	return nil
}

func init() {
	proto.RegisterExtension(E_FriendInvitation_FriendInvite)
	proto.RegisterExtension(E_FriendInvitationParams_FriendParams)
}
