// Code generated by protoc-gen-go.
// source: bnet/protocol/presence.proto
// DO NOT EDIT!

/*
Package bnet_protocol_presence is a generated protocol buffer package.

It is generated from these files:
	bnet/protocol/presence.proto

It has these top-level messages:
	FieldKey
	Field
	FieldOperation
	ChannelState
	OwnershipRequest
	QueryRequest
	QueryResponse
	RichPresence
	SubscribeNotificationRequest
	SubscribeRequest
	UnsubscribeRequest
	UpdateRequest
*/
package bnet_protocol_presence

import proto "github.com/golang/protobuf/proto"
import math "math"
import bnet_protocol_attribute "bnet/protocol"
import bnet_protocol "bnet"
import bnet_protocol_channel "bnet/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FieldOperation_OperationType int32

const (
	FieldOperation_SET   FieldOperation_OperationType = 0
	FieldOperation_CLEAR FieldOperation_OperationType = 1
)

var FieldOperation_OperationType_name = map[int32]string{
	0: "SET",
	1: "CLEAR",
}
var FieldOperation_OperationType_value = map[string]int32{
	"SET":   0,
	"CLEAR": 1,
}

func (x FieldOperation_OperationType) Enum() *FieldOperation_OperationType {
	p := new(FieldOperation_OperationType)
	*p = x
	return p
}
func (x FieldOperation_OperationType) String() string {
	return proto.EnumName(FieldOperation_OperationType_name, int32(x))
}
func (x *FieldOperation_OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldOperation_OperationType_value, data, "FieldOperation_OperationType")
	if err != nil {
		return err
	}
	*x = FieldOperation_OperationType(value)
	return nil
}

type FieldKey struct {
	Program          *uint32 `protobuf:"varint,1,opt,name=program" json:"program,omitempty"`
	Group            *uint32 `protobuf:"varint,2,opt,name=group" json:"group,omitempty"`
	Field            *uint32 `protobuf:"varint,3,opt,name=field" json:"field,omitempty"`
	Index            *uint64 `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FieldKey) Reset()         { *m = FieldKey{} }
func (m *FieldKey) String() string { return proto.CompactTextString(m) }
func (*FieldKey) ProtoMessage()    {}

func (m *FieldKey) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

func (m *FieldKey) GetGroup() uint32 {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return 0
}

func (m *FieldKey) GetField() uint32 {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return 0
}

func (m *FieldKey) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type Field struct {
	Key              *FieldKey                        `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *bnet_protocol_attribute.Variant `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}

func (m *Field) GetKey() *FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Field) GetValue() *bnet_protocol_attribute.Variant {
	if m != nil {
		return m.Value
	}
	return nil
}

type FieldOperation struct {
	Field            *Field                        `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Operation        *FieldOperation_OperationType `protobuf:"varint,2,opt,name=operation,enum=bnet.protocol.presence.FieldOperation_OperationType" json:"operation,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *FieldOperation) Reset()         { *m = FieldOperation{} }
func (m *FieldOperation) String() string { return proto.CompactTextString(m) }
func (*FieldOperation) ProtoMessage()    {}

func (m *FieldOperation) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *FieldOperation) GetOperation() FieldOperation_OperationType {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return FieldOperation_SET
}

type ChannelState struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id" json:"entity_id,omitempty"`
	FieldOperation   []*FieldOperation       `protobuf:"bytes,2,rep,name=field_operation" json:"field_operation,omitempty"`
	Healing          *bool                   `protobuf:"varint,3,opt,name=healing" json:"healing,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ChannelState) Reset()         { *m = ChannelState{} }
func (m *ChannelState) String() string { return proto.CompactTextString(m) }
func (*ChannelState) ProtoMessage()    {}

func (m *ChannelState) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *ChannelState) GetFieldOperation() []*FieldOperation {
	if m != nil {
		return m.FieldOperation
	}
	return nil
}

func (m *ChannelState) GetHealing() bool {
	if m != nil && m.Healing != nil {
		return *m.Healing
	}
	return false
}

var E_ChannelState_Presence = &proto.ExtensionDesc{
	ExtendedType:  (*bnet_protocol_channel.ChannelState)(nil),
	ExtensionType: (*ChannelState)(nil),
	Field:         101,
	Name:          "bnet.protocol.presence.ChannelState.presence",
	Tag:           "bytes,101,opt,name=presence",
}

type OwnershipRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id" json:"entity_id,omitempty"`
	ReleaseOwnership *bool                   `protobuf:"varint,2,opt,name=release_ownership" json:"release_ownership,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *OwnershipRequest) Reset()         { *m = OwnershipRequest{} }
func (m *OwnershipRequest) String() string { return proto.CompactTextString(m) }
func (*OwnershipRequest) ProtoMessage()    {}

func (m *OwnershipRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *OwnershipRequest) GetReleaseOwnership() bool {
	if m != nil && m.ReleaseOwnership != nil {
		return *m.ReleaseOwnership
	}
	return false
}

type QueryRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id" json:"entity_id,omitempty"`
	Key              []*FieldKey             `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}

func (m *QueryRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *QueryRequest) GetKey() []*FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type QueryResponse struct {
	Field            []*Field `protobuf:"bytes,2,rep,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}

func (m *QueryResponse) GetField() []*Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type RichPresence struct {
	ProgramId        *uint32 `protobuf:"fixed32,1,opt,name=program_id" json:"program_id,omitempty"`
	StreamId         *uint32 `protobuf:"fixed32,2,opt,name=stream_id" json:"stream_id,omitempty"`
	Index            *uint32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RichPresence) Reset()         { *m = RichPresence{} }
func (m *RichPresence) String() string { return proto.CompactTextString(m) }
func (*RichPresence) ProtoMessage()    {}

func (m *RichPresence) GetProgramId() uint32 {
	if m != nil && m.ProgramId != nil {
		return *m.ProgramId
	}
	return 0
}

func (m *RichPresence) GetStreamId() uint32 {
	if m != nil && m.StreamId != nil {
		return *m.StreamId
	}
	return 0
}

func (m *RichPresence) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type SubscribeNotificationRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id" json:"entity_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SubscribeNotificationRequest) Reset()         { *m = SubscribeNotificationRequest{} }
func (m *SubscribeNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeNotificationRequest) ProtoMessage()    {}

func (m *SubscribeNotificationRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

type SubscribeRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=entity_id" json:"entity_id,omitempty"`
	ObjectId         *uint64                 `protobuf:"varint,3,opt,name=object_id" json:"object_id,omitempty"`
	ProgramId        []uint32                `protobuf:"fixed32,4,rep,name=program_id" json:"program_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}

func (m *SubscribeRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *SubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *SubscribeRequest) GetProgramId() []uint32 {
	if m != nil {
		return m.ProgramId
	}
	return nil
}

type UnsubscribeRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id" json:"agent_id,omitempty"`
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=entity_id" json:"entity_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}

func (m *UnsubscribeRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

type UpdateRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id" json:"entity_id,omitempty"`
	FieldOperation   []*FieldOperation       `protobuf:"bytes,2,rep,name=field_operation" json:"field_operation,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}

func (m *UpdateRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *UpdateRequest) GetFieldOperation() []*FieldOperation {
	if m != nil {
		return m.FieldOperation
	}
	return nil
}

func init() {
	proto.RegisterEnum("bnet.protocol.presence.FieldOperation_OperationType", FieldOperation_OperationType_name, FieldOperation_OperationType_value)
	proto.RegisterExtension(E_ChannelState_Presence)
}
