# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bnet/protocol/risk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bnet/protocol/risk.proto',
  package='bnet.protocol.risk',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x62net/protocol/risk.proto\x12\x12\x62net.protocol.risk\"%\n\x08\x45ntityId\x12\x0c\n\x04high\x18\x01 \x01(\x06\x12\x0b\n\x03low\x18\x02 \x01(\x06\"C\n\x18ReportMeterEventResponse\x12\x14\n\x0cpenalty_secs\x18\x01 \x01(\x04\x12\x11\n\tthreshold\x18\x02 \x01(\x04\"\xe6\x01\n\x07Variant\x12\x12\n\nbool_value\x18\x02 \x01(\x08\x12\x11\n\tint_value\x18\x03 \x01(\x03\x12\x13\n\x0b\x66loat_value\x18\x04 \x01(\x01\x12\x14\n\x0cstring_value\x18\x05 \x01(\t\x12\x12\n\nblob_value\x18\x06 \x01(\x0c\x12\x15\n\rmessage_value\x18\x07 \x01(\x0c\x12\x14\n\x0c\x66ourcc_value\x18\x08 \x01(\t\x12\x12\n\nuint_value\x18\t \x01(\x04\x12\x34\n\x0e\x65ntityid_value\x18\n \x01(\x0b\x32\x1c.bnet.protocol.risk.EntityId\"E\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.bnet.protocol.risk.Variant\"\xa4\x01\n\x17ReportMeterEventRequest\x12\x12\n\nmeter_type\x18\x01 \x01(\x07\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t\x12\x1f\n\x17\x61\x64\x64itional_penalty_secs\x18\x04 \x01(\x04\x12\x30\n\tattribute\x18\x05 \x03(\x0b\x32\x1d.bnet.protocol.risk.Attribute')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTITYID = _descriptor.Descriptor(
  name='EntityId',
  full_name='bnet.protocol.risk.EntityId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='high', full_name='bnet.protocol.risk.EntityId.high', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low', full_name='bnet.protocol.risk.EntityId.low', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=85,
)


_REPORTMETEREVENTRESPONSE = _descriptor.Descriptor(
  name='ReportMeterEventResponse',
  full_name='bnet.protocol.risk.ReportMeterEventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='penalty_secs', full_name='bnet.protocol.risk.ReportMeterEventResponse.penalty_secs', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='bnet.protocol.risk.ReportMeterEventResponse.threshold', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=154,
)


_VARIANT = _descriptor.Descriptor(
  name='Variant',
  full_name='bnet.protocol.risk.Variant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='bnet.protocol.risk.Variant.bool_value', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='bnet.protocol.risk.Variant.int_value', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='bnet.protocol.risk.Variant.float_value', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='bnet.protocol.risk.Variant.string_value', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blob_value', full_name='bnet.protocol.risk.Variant.blob_value', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_value', full_name='bnet.protocol.risk.Variant.message_value', index=5,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fourcc_value', full_name='bnet.protocol.risk.Variant.fourcc_value', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint_value', full_name='bnet.protocol.risk.Variant.uint_value', index=7,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entityid_value', full_name='bnet.protocol.risk.Variant.entityid_value', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=387,
)


_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='bnet.protocol.risk.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.risk.Attribute.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='bnet.protocol.risk.Attribute.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=458,
)


_REPORTMETEREVENTREQUEST = _descriptor.Descriptor(
  name='ReportMeterEventRequest',
  full_name='bnet.protocol.risk.ReportMeterEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meter_type', full_name='bnet.protocol.risk.ReportMeterEventRequest.meter_type', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='bnet.protocol.risk.ReportMeterEventRequest.event_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='bnet.protocol.risk.ReportMeterEventRequest.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='additional_penalty_secs', full_name='bnet.protocol.risk.ReportMeterEventRequest.additional_penalty_secs', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.risk.ReportMeterEventRequest.attribute', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=625,
)

_VARIANT.fields_by_name['entityid_value'].message_type = _ENTITYID
_ATTRIBUTE.fields_by_name['value'].message_type = _VARIANT
_REPORTMETEREVENTREQUEST.fields_by_name['attribute'].message_type = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['EntityId'] = _ENTITYID
DESCRIPTOR.message_types_by_name['ReportMeterEventResponse'] = _REPORTMETEREVENTRESPONSE
DESCRIPTOR.message_types_by_name['Variant'] = _VARIANT
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['ReportMeterEventRequest'] = _REPORTMETEREVENTREQUEST

EntityId = _reflection.GeneratedProtocolMessageType('EntityId', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYID,
  __module__ = 'bnet.protocol.risk_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.risk.EntityId)
  ))
_sym_db.RegisterMessage(EntityId)

ReportMeterEventResponse = _reflection.GeneratedProtocolMessageType('ReportMeterEventResponse', (_message.Message,), dict(
  DESCRIPTOR = _REPORTMETEREVENTRESPONSE,
  __module__ = 'bnet.protocol.risk_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.risk.ReportMeterEventResponse)
  ))
_sym_db.RegisterMessage(ReportMeterEventResponse)

Variant = _reflection.GeneratedProtocolMessageType('Variant', (_message.Message,), dict(
  DESCRIPTOR = _VARIANT,
  __module__ = 'bnet.protocol.risk_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.risk.Variant)
  ))
_sym_db.RegisterMessage(Variant)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTE,
  __module__ = 'bnet.protocol.risk_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.risk.Attribute)
  ))
_sym_db.RegisterMessage(Attribute)

ReportMeterEventRequest = _reflection.GeneratedProtocolMessageType('ReportMeterEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPORTMETEREVENTREQUEST,
  __module__ = 'bnet.protocol.risk_pb2'
  # @@protoc_insertion_point(class_scope:bnet.protocol.risk.ReportMeterEventRequest)
  ))
_sym_db.RegisterMessage(ReportMeterEventRequest)


# @@protoc_insertion_point(module_scope)
