// Code generated by protoc-gen-go.
// source: SimpleJSON.proto
// DO NOT EDIT!

/*
Package SimpleJSON is a generated protocol buffer package.

It is generated from these files:
	SimpleJSON.proto

It has these top-level messages:
*/
package SimpleJSON

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type JSONBinaryTag int32

const (
	JSONBinaryTag_Array       JSONBinaryTag = 1
	JSONBinaryTag_Class       JSONBinaryTag = 2
	JSONBinaryTag_Value       JSONBinaryTag = 3
	JSONBinaryTag_IntValue    JSONBinaryTag = 4
	JSONBinaryTag_DoubleValue JSONBinaryTag = 5
	JSONBinaryTag_BoolValue   JSONBinaryTag = 6
	JSONBinaryTag_FloatValue  JSONBinaryTag = 7
)

var JSONBinaryTag_name = map[int32]string{
	1: "Array",
	2: "Class",
	3: "Value",
	4: "IntValue",
	5: "DoubleValue",
	6: "BoolValue",
	7: "FloatValue",
}
var JSONBinaryTag_value = map[string]int32{
	"Array":       1,
	"Class":       2,
	"Value":       3,
	"IntValue":    4,
	"DoubleValue": 5,
	"BoolValue":   6,
	"FloatValue":  7,
}

func (x JSONBinaryTag) Enum() *JSONBinaryTag {
	p := new(JSONBinaryTag)
	*p = x
	return p
}
func (x JSONBinaryTag) String() string {
	return proto.EnumName(JSONBinaryTag_name, int32(x))
}
func (x *JSONBinaryTag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(JSONBinaryTag_value, data, "JSONBinaryTag")
	if err != nil {
		return err
	}
	*x = JSONBinaryTag(value)
	return nil
}

func init() {
	proto.RegisterEnum("SimpleJSON.JSONBinaryTag", JSONBinaryTag_name, JSONBinaryTag_value)
}
